### ISSUE TITLE
you die before you can actually become assimilated

### ISSUE THREAD

**Issue by sealymcsealer** [FakeACat/FromAnotherWorld#2]
like if there some things chasing you its VERY unlikely you'll actually become assimilated i think the slow assimilation should kill you instead of needing it to go up to x or the slow assimilation slowly go up a phase each time it runs out because you just die before that can happen

**Comment by FakeACat** [comment]
That is intentional, to minimise the chance of spawnkilling the player by infinitely creating more assimilated players if they get to your spawnpoint.
